'use strict';

const confusingBrowserGlobals = require('confusing-browser-globals');

const OFF = 'off';
const WARN = 'warn';
const ERROR = 'error';

module.exports = {
  env: {
    es2022: true,
  },
  parserOptions: {
    ecmaVersion: 'latest',
  },
  plugins: ['import'],
  settings: {
    'import/extensions': ['.js', '.mjs', '.cjs'],
    'import/resolver': {
      node: {
        extensions: ['.js', '.mjs', '.cjs'],
      },
    },
  },
  reportUnusedDisableDirectives: true,
  rules: {
    // Possible Problems ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    'array-callback-return': [
      ERROR,
      {
        allowImplicit: false,
        checkForEach: true,
      },
    ],
    'constructor-super': ERROR,
    'for-direction': ERROR,
    'getter-return': [
      ERROR,
      {
        allowImplicit: false,
      },
    ],
    'no-async-promise-executor': ERROR,
    'no-await-in-loop': OFF,
    'no-class-assign': ERROR,
    'no-compare-neg-zero': ERROR,
    'no-cond-assign': [ERROR, 'always'],
    'no-const-assign': ERROR,
    'no-constant-binary-expression': ERROR,
    'no-constant-condition': ERROR,
    'no-constructor-return': ERROR,
    'no-control-regex': ERROR,
    'no-debugger': ERROR,
    'no-dupe-args': ERROR,
    'no-dupe-class-members': ERROR,
    'no-dupe-else-if': ERROR,
    'no-dupe-keys': ERROR,
    'no-duplicate-case': ERROR,
    'no-duplicate-imports': OFF, // Handled by the import plugin
    'no-empty-character-class': ERROR,
    'no-empty-pattern': ERROR,
    'no-ex-assign': ERROR,
    'no-fallthrough': [
      ERROR,
      {
        allowEmptyCase: true,
      },
    ],
    'no-func-assign': ERROR,
    'no-import-assign': ERROR,
    'no-inner-declarations': ERROR,
    'no-invalid-regexp': ERROR,
    'no-irregular-whitespace': ERROR,
    'no-loss-of-precision': ERROR,
    'no-misleading-character-class': ERROR,
    'no-new-native-nonconstructor': ERROR,
    'no-new-symbol': OFF, // Handled by the no-new-native-nonconstructor rule
    'no-obj-calls': ERROR,
    'no-promise-executor-return': ERROR,
    'no-prototype-builtins': ERROR,
    'no-self-assign': [
      ERROR,
      {
        props: true,
      },
    ],
    'no-self-compare': ERROR,
    'no-setter-return': ERROR,
    'no-sparse-arrays': ERROR,
    'no-template-curly-in-string': ERROR,
    'no-this-before-super': ERROR,
    'no-undef': ERROR,
    'no-unexpected-multiline': ERROR,
    'no-unmodified-loop-condition': ERROR,
    'no-unreachable': ERROR,
    'no-unreachable-loop': ERROR,
    'no-unsafe-finally': ERROR,
    'no-unsafe-negation': [
      ERROR,
      {
        enforceForOrderingRelations: true,
      },
    ],
    'no-unsafe-optional-chaining': [
      ERROR,
      {
        disallowArithmeticOperators: true,
      },
    ],
    'no-unused-private-class-members': ERROR,
    'no-unused-vars': [
      ERROR,
      {
        vars: 'all',
        args: 'after-used',
        ignoreRestSiblings: true,
      },
    ],
    'no-use-before-define': [
      ERROR,
      {
        classes: true,
        functions: true,
        variables: true,
        allowNamedExports: false,
      },
    ],
    'no-useless-backreference': ERROR,
    'require-atomic-updates': ERROR,
    'use-isnan': [
      ERROR,
      {
        enforceForIndexOf: true,
        enforceForSwitchCase: true,
      },
    ],
    'valid-typeof': [
      ERROR,
      {
        requireStringLiterals: true,
      },
    ],

    // Suggestions ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    'accessor-pairs': OFF,
    'arrow-body-style': OFF,
    'block-scoped-var': ERROR,
    'camelcase': [
      ERROR,
      {
        ignoreDestructuring: true,
        ignoreGlobals: true,
        ignoreImports: true,
        properties: 'always',
      },
    ],
    'capitalized-comments': OFF,
    'class-methods-use-this': ERROR,
    'complexity': OFF,
    'consistent-return': ERROR,
    'consistent-this': OFF,
    'curly': [ERROR, 'all'],
    'default-case': ERROR,
    'default-case-last': ERROR,
    'default-param-last': ERROR,
    'dot-notation': ERROR,
    'eqeqeq': [
      ERROR,
      'always',
      {
        null: 'ignore',
      },
    ],
    'func-name-matching': [
      ERROR,
      'always',
      {
        considerPropertyDescriptor: true,
        includeCommonJSModuleExports: false,
      },
    ],
    'func-names': [ERROR, 'as-needed'],
    'func-style': [ERROR, 'declaration'],
    'grouped-accessor-pairs': [ERROR, 'getBeforeSet'],
    'guard-for-in': ERROR,
    'id-denylist': OFF,
    'id-length': OFF,
    'id-match': OFF,
    'init-declarations': OFF,
    'logical-assignment-operators': OFF,
    'max-classes-per-file': [ERROR, 1],
    'max-depth': OFF,
    'max-lines': OFF,
    'max-lines-per-function': OFF,
    'max-nested-callbacks': OFF,
    'max-params': OFF,
    'max-statements': OFF,
    'multiline-comment-style': OFF,
    'new-cap': [
      ERROR,
      {
        newIsCap: true,
        capIsNew: false,
        properties: true,
      },
    ],
    'no-alert': ERROR,
    'no-array-constructor': ERROR,
    'no-bitwise': OFF,
    'no-caller': ERROR,
    'no-case-declarations': ERROR,
    'no-confusing-arrow': ERROR,
    'no-console': ERROR,
    'no-continue': ERROR,
    'no-delete-var': ERROR,
    'no-div-regex': ERROR,
    'no-else-return': [
      ERROR,
      {
        allowElseIf: false,
      },
    ],
    'no-empty': ERROR,
    'no-empty-function': ERROR,
    'no-empty-static-block': ERROR,
    'no-eq-null': OFF,
    'no-eval': ERROR,
    'no-extend-native': ERROR,
    'no-extra-bind': ERROR,
    'no-extra-boolean-cast': [
      ERROR,
      {
        enforceForLogicalOperands: true,
      },
    ],
    'no-extra-label': ERROR,
    'no-extra-semi': ERROR,
    'no-floating-decimal': ERROR,
    'no-global-assign': ERROR,
    'no-implicit-coercion': ERROR,
    'no-implicit-globals': ERROR,
    'no-implied-eval': ERROR,
    'no-inline-comments': OFF,
    'no-invalid-this': ERROR,
    'no-iterator': ERROR,
    'no-label-var': ERROR,
    'no-labels': [
      ERROR,
      {
        allowLoop: true,
        allowSwitch: true,
      },
    ],
    'no-lone-blocks': ERROR,
    'no-lonely-if': ERROR,
    'no-loop-func': ERROR,
    'no-magic-numbers': OFF,
    'no-mixed-operators': ERROR,
    'no-multi-assign': ERROR,
    'no-multi-str': ERROR,
    'no-negated-condition': ERROR,
    'no-nested-ternary': ERROR,
    'no-new': ERROR,
    'no-new-func': ERROR,
    'no-new-object': ERROR,
    'no-new-wrappers': ERROR,
    'no-nonoctal-decimal-escape': ERROR,
    'no-octal': ERROR,
    'no-octal-escape': ERROR,
    'no-param-reassign': ERROR,
    'no-plusplus': [
      ERROR,
      {
        allowForLoopAfterthoughts: true,
      },
    ],
    'no-proto': ERROR,
    'no-redeclare': ERROR,
    'no-regex-spaces': ERROR,
    'no-restricted-exports': [
      ERROR,
      {
        restrictedNamedExports: ['default', 'then'],
      },
    ],
    'no-restricted-globals': [ERROR, ...confusingBrowserGlobals],
    'no-restricted-imports': OFF,
    'no-restricted-properties': OFF,
    'no-restricted-syntax': OFF,
    'no-return-assign': [ERROR, 'always'],
    'no-return-await': ERROR,
    'no-script-url': ERROR,
    'no-sequences': ERROR,
    'no-shadow': [
      ERROR,
      {
        allow: confusingBrowserGlobals,
        builtinGlobals: true,
        ignoreOnInitialization: true,
      },
    ],
    'no-shadow-restricted-names': ERROR,
    'no-ternary': OFF,
    'no-throw-literal': ERROR,
    'no-undef-init': ERROR,
    'no-undefined': ERROR,
    'no-underscore-dangle': ERROR,
    'no-unneeded-ternary': ERROR,
    'no-unused-expressions': [
      ERROR,
      {
        allowShortCircuit: false,
        allowTernary: false,
        enforceForJSX: true,
      },
    ],
    'no-unused-labels': ERROR,
    'no-useless-call': ERROR,
    'no-useless-catch': ERROR,
    'no-useless-computed-key': [
      ERROR,
      {
        enforceForClassMembers: true,
      },
    ],
    'no-useless-concat': ERROR,
    'no-useless-constructor': ERROR,
    'no-useless-escape': ERROR,
    'no-useless-rename': ERROR,
    'no-useless-return': ERROR,
    'no-var': ERROR,
    'no-void': ERROR,
    'no-warning-comments': OFF,
    'no-with': ERROR,
    'object-shorthand': [
      ERROR,
      'always',
      {
        avoidQuotes: true,
        ignoreConstructors: false,
        avoidExplicitReturnArrows: true,
      },
    ],
    'one-var': [ERROR, 'never'],
    'one-var-declaration-per-line': ERROR,
    'operator-assignment': [ERROR, 'always'],
    'prefer-arrow-callback': [
      ERROR,
      {
        allowNamedFunctions: true,
        allowUnboundThis: false,
      },
    ],
    'prefer-const': [
      ERROR,
      {
        destructuring: 'all',
        ignoreReadBeforeAssign: true,
      },
    ],
    'prefer-destructuring': OFF,
    'prefer-exponentiation-operator': ERROR,
    'prefer-named-capture-group': OFF,
    'prefer-numeric-literals': ERROR,
    'prefer-object-has-own': ERROR,
    'prefer-object-spread': ERROR,
    'prefer-promise-reject-errors': ERROR,
    'prefer-regex-literals': ERROR,
    'prefer-rest-params': ERROR,
    'prefer-spread': ERROR,
    'prefer-template': ERROR,
    'quote-props': [ERROR, 'consistent-as-needed'],
    'radix': [ERROR, 'always'],
    'require-await': ERROR,
    'require-unicode-regexp': ERROR,
    'require-yield': ERROR,
    'sort-imports': OFF, // Handled by the import plugin
    'sort-keys': OFF,
    'sort-vars': OFF,
    'spaced-comment': [ERROR, 'always'],
    'strict': [ERROR, 'global'],
    'symbol-description': ERROR,
    'vars-on-top': ERROR,
    'yoda': ERROR,

    // Style rules ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    'array-bracket-newline': OFF,
    'array-bracket-spacing': OFF,
    'array-element-newline': OFF,
    'arrow-parens': OFF,
    'arrow-spacing': OFF,
    'block-spacing': OFF,
    'brace-style': OFF,
    'comma-dangle': OFF,
    'comma-spacing': OFF,
    'comma-style': OFF,
    'computed-property-spacing': OFF,
    'dot-location': OFF,
    'eol-last': OFF,
    'func-call-spacing': OFF,
    'function-call-argument-newline': OFF,
    'function-paren-newline': OFF,
    'generator-star-spacing': OFF,
    'implicit-arrow-linebreak': OFF,
    'indent': OFF,
    'jsx-quotes': OFF,
    'key-spacing': OFF,
    'keyword-spacing': OFF,
    'line-comment-position': OFF,
    'linebreak-style': OFF,
    'lines-around-comment': OFF,
    'lines-between-class-members': OFF,
    'max-len': OFF,
    'max-statements-per-line': OFF,
    'multiline-ternary': OFF,
    'new-parens': OFF,
    'newline-per-chained-call': OFF,
    'no-extra-parens': OFF,
    'no-mixed-spaces-and-tabs': OFF,
    'no-multi-spaces': OFF,
    'no-multiple-empty-lines': OFF,
    'no-tabs': OFF,
    'no-trailing-spaces': OFF,
    'no-whitespace-before-property': OFF,
    'nonblock-statement-body-position': OFF,
    'object-curly-newline': OFF,
    'object-curly-spacing': OFF,
    'object-property-newline': OFF,
    'operator-linebreak': OFF,
    'padded-blocks': OFF,
    'padding-line-between-statements': OFF,
    'quotes': OFF,
    'rest-spread-spacing': OFF,
    'semi': OFF,
    'semi-spacing': OFF,
    'semi-style': OFF,
    'space-before-blocks': OFF,
    'space-before-function-paren': OFF,
    'space-in-parens': OFF,
    'space-infix-ops': OFF,
    'space-unary-ops': OFF,
    'switch-colon-spacing': OFF,
    'template-curly-spacing': OFF,
    'template-tag-spacing': OFF,
    'unicode-bom': OFF,
    'wrap-iife': OFF,
    'wrap-regex': OFF,
    'yield-star-spacing': OFF,

    // Import ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    'import/default': ERROR,
    'import/dynamic-import-chunkname': OFF, // Enable if using WebPack
    'import/export': ERROR,
    'import/exports-last': OFF,
    'import/extensions': [ERROR, 'ignorePackages'],
    'import/first': ERROR,
    'import/group-exports': OFF,
    'import/max-dependencies': OFF,
    'import/named': ERROR,
    'import/namespace': ERROR,
    'import/newline-after-import': ERROR,
    'import/no-absolute-path': ERROR,
    'import/no-amd': ERROR,
    'import/no-anonymous-default-export': [
      ERROR,
      {
        allowArray: false,
        allowArrowFunction: false,
        allowAnonymousClass: false,
        allowAnonymousFunction: false,
        allowCallExpression: false,
        allowLiteral: false,
        allowObject: false,
      },
    ],
    'import/no-commonjs': ERROR,
    'import/no-cycle': [
      ERROR,
      {
        ignoreExternal: true,
      },
    ],
    'import/no-default-export': ERROR,
    'import/no-deprecated': WARN,
    'import/no-duplicates': [
      ERROR,
      {
        considerQueryString: true,
      },
    ],
    'import/no-dynamic-require': ERROR,
    'import/no-extraneous-dependencies': [
      ERROR,
      {
        devDependencies: false,
        optionalDependencies: true,
        peerDependencies: true,
      },
    ],
    'import/no-import-module-exports': ERROR,
    'import/no-internal-modules': OFF,
    'import/no-mutable-exports': ERROR,
    'import/no-named-as-default': ERROR,
    'import/no-named-as-default-member': OFF,
    'import/no-named-default': ERROR,
    'import/no-named-export': OFF,
    'import/no-namespace': ERROR,
    'import/no-nodejs-modules': ERROR,
    'import/no-relative-packages': OFF,
    'import/no-relative-parent-imports': OFF,
    'import/no-restricted-paths': OFF,
    'import/no-self-import': ERROR,
    'import/no-unassigned-import': ERROR,
    'import/no-unresolved': ERROR,
    'import/no-unused-modules': OFF, // Prevents incremental development
    'import/no-useless-path-segments': ERROR,
    'import/no-webpack-loader-syntax': ERROR,
    'import/order': [
      ERROR,
      {
        'groups': ['builtin', 'external', 'internal', ['parent', 'sibling']],
        'newlines-between': 'always',
        'alphabetize': {
          order: 'asc',
          caseInsensitive: true,
        },
      },
    ],
    'import/prefer-default-export': OFF,
    'import/unambiguous': ERROR,
  },
};
